package org.example.project.presentation.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.compositionLocalOf
import org.example.project.domain.accounts.AccountRole
import org.example.project.domain.auth.UserRole
import org.example.project.domain.project.ProjectStatus
import org.example.project.domain.returns.ReturnStatus
import org.example.project.domain.task.TaskStatus

enum class AppLanguage(
    val code: String,
    val label: String,
) {
    EN("en", "EN"),
    RO("ro", "RO"),
    DE("de", "DE");

    companion object {
        fun fromCode(code: String?): AppLanguage =
            values().firstOrNull { it.code.equals(code, ignoreCase = true) } ?: EN
    }
}

@Immutable
class AppStrings(
    private val language: AppLanguage,
) {
    fun text(key: String): String =
        translations[language]?.get(key) ?: translations[AppLanguage.EN]?.get(key) ?: key

    fun format(key: String, vararg values: Pair<String, String>): String {
        var value = text(key)
        values.forEach { (name, replacement) ->
            value = value.replace("{$name}", replacement)
        }
        return value
    }

    fun taskStatus(status: TaskStatus): String =
        text(
            when (status) {
                TaskStatus.TO_DO -> "To do"
                TaskStatus.IN_PROGRESS -> "In progress"
                TaskStatus.COMPLETE -> "Complete"
                TaskStatus.BLOCKED -> "Blocked"
            }
        )

    fun projectStatus(status: ProjectStatus): String =
        text(
            when (status) {
                ProjectStatus.TO_DO -> "To do"
                ProjectStatus.IN_PROGRESS -> "In progress"
                ProjectStatus.COMPLETE -> "Complete"
                ProjectStatus.BLOCKED -> "Blocked"
            }
        )

    fun accountRole(role: AccountRole): String =
        text(
            when (role) {
                AccountRole.ADMIN -> "Admin"
                AccountRole.EMPLOYEE -> "Employee"
            }
        )

    fun userRole(role: UserRole): String =
        text(
            when (role) {
                UserRole.ADMIN -> "Administrator"
                UserRole.EMPLOYEE -> "Employee"
            }
        )

    fun accountStatus(status: String): String =
        text(status.ifBlank { "Unknown" }.lowercase().replaceFirstChar { it.uppercase() })

    fun returnStatus(status: ReturnStatus): String =
        text(
            when (status) {
                ReturnStatus.REQUESTED -> "Requested"
                ReturnStatus.APPROVED -> "Approved"
                ReturnStatus.REJECTED -> "Rejected"
                ReturnStatus.RECEIVED -> "Received"
                ReturnStatus.REFUNDED -> "Refunded"
            }
        )
}

val LocalAppLanguage = compositionLocalOf { AppLanguage.EN }
val LocalAppStrings = compositionLocalOf { AppStrings(AppLanguage.EN) }

@Composable
fun AppLocalizationProvider(
    language: AppLanguage,
    content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
        LocalAppLanguage provides language,
        LocalAppStrings provides AppStrings(language),
        content = content,
    )
}

private val translations = mapOf(
    AppLanguage.EN to mapOf(
        "Dashboard" to "Dashboard",
        "Workspace" to "Workspace",
        "Sales" to "Sales",
        "Tasks" to "Tasks",
        "Projects" to "Projects",
        "Chat" to "Chat",
        "Stock" to "Stock",
        "Orders" to "Orders",
        "Returns" to "Returns",
        "Admin" to "Admin",
        "Sign in" to "Sign in",
        "Email" to "Email",
        "Password" to "Password",
        "Enter your email" to "Enter your email",
        "Enter your password" to "Enter your password",
        "Login" to "Login",
        "Could not connect to backend." to "Could not connect to backend.",
        "Login failed." to "Login failed.",
        "Logged in as {name}" to "Logged in as {name}",
        "Account" to "Account",
        "Phone" to "Phone",
        "Phone number" to "Phone number",
        "Status" to "Status",
        "Role" to "Role",
        "Language" to "Language",
        "Log out" to "Log out",
        "Close" to "Close",
        "Administrator" to "Administrator",
        "Employee" to "Employee",
        "Available" to "Available",
        "Busy" to "Busy",
        "Away" to "Away",
        "Unknown" to "Unknown",
        "Good evening, {name}." to "Good evening, {name}.",
        "Due today" to "Due today",
        "{count} task" to "{count} task",
        "{count} tasks" to "{count} tasks",
        "No tasks due today." to "No tasks due today.",
        "Online now" to "Online now",
        "{count} person" to "{count} person",
        "{count} people" to "{count} people",
        "No project" to "No project",
        "Unassigned" to "Unassigned",
        "Search tasks..." to "Search tasks...",
        "+ Add task" to "+ Add task",
        "My tasks" to "My tasks",
        "All" to "All",
        "To do" to "To do",
        "In progress" to "In progress",
        "Complete" to "Complete",
        "Blocked" to "Blocked",
        "Task" to "Task",
        "Add task" to "Add task",
        "Due" to "Due",
        "Project" to "Project",
        "Assignees" to "Assignees",
        "Save task" to "Save task",
        "Cancel" to "Cancel",
        "Edit task" to "Edit task",
        "Save changes" to "Save changes",
        "Saving..." to "Saving...",
        "Description" to "Description",
        "Assigned to" to "Assigned to",
        "Subtasks" to "Subtasks",
        "Add subtask" to "Add subtask",
        "Subtask title" to "Subtask title",
        "Create subtask" to "Create subtask",
        "No subtasks yet" to "No subtasks yet",
        "Delete parent task warning" to "Deleting this task may turn its subtasks into top-level tasks.",
        "+ Assign" to "+ Assign",
        "Search by name..." to "Search by name...",
        "No users found" to "No users found",
        "Time tracking" to "Time tracking",
        "Total task" to "Total task",
        "Start timer" to "Start timer",
        "Stop timer" to "Stop timer",
        "Search projects..." to "Search projects...",
        "+ Add project" to "+ Add project",
        "Project" to "Project",
        "Deadline" to "Deadline",
        "No tasks in this project yet." to "No tasks in this project yet.",
        "Add project" to "Add project",
        "Save project" to "Save project",
        "Search products..." to "Search products...",
        "+ Add product" to "+ Add product",
        "Add product" to "Add product",
        "Product" to "Product",
        "Product name" to "Product name",
        "Image URL" to "Image URL",
        "Price" to "Price",
        "Weight" to "Weight",
        "Weight unit" to "Weight unit",
        "Stock quantity" to "Stock quantity",
        "Out of stock" to "Out of stock",
        "{count} products" to "{count} products",
        "{count} low stock" to "{count} low stock",
        "{count} out of stock" to "{count} out of stock",
        "Save product" to "Save product",
        "Previous" to "Previous",
        "Next" to "Next",
        "Phone number is required." to "Phone number is required.",
        "Phone number is too long." to "Phone number is too long.",
        "Edit" to "Edit",
        "Quantity" to "Quantity",
        "Save" to "Save",
        "Add user" to "Add user",
        "Full name" to "Full name",
        "Language flag" to "Language flag",
        "Save user" to "Save user",
        "Search users..." to "Search users...",
        "+ Add user" to "+ Add user",
        "User" to "User",
        "Active" to "Active",
        "Inactive" to "Inactive",
        "Actions" to "Actions",
        "Deactivate" to "Deactivate",
        "Reactivate" to "Reactivate",
        "Deactivate account?" to "Deactivate account?",
        "Reactivate account?" to "Reactivate account?",
        "Are you sure you want to deactivate {name}?" to "Are you sure you want to deactivate {name}?",
        "Are you sure you want to reactivate {name}?" to "Are you sure you want to reactivate {name}?",
        "Page {page} of {total}" to "Page {page} of {total}",
        "{count} users" to "{count} users",
        "Search chat or person..." to "Search chat or person...",
        "No chats found." to "No chats found.",
        "Write a message..." to "Write a message...",
        "Send" to "Send",
        "Unknown sender" to "Unknown",
        "New group" to "New group",
        "GROUP" to "GROUP",
        "Create group" to "Create group",
        "Edit group" to "Edit group",
        "Group name" to "Group name",
        "Add members" to "Add members",
        "Current members" to "Current members",
        "Search people..." to "Search people...",
        "Create" to "Create",
        "Settings" to "Settings",
        "Audio call" to "Audio call",
        "Video call" to "Video call",
        "Group audio" to "Group audio",
        "Group video" to "Group video",
        "Call history" to "Call history",
        "No calls found." to "No calls found.",
        "Incoming video call" to "Incoming video call",
        "Incoming audio call" to "Incoming audio call",
        "Group call" to "Group call",
        "Lumi Workspace call" to "Lumi Workspace call",
        "Decline" to "Decline",
        "Answer" to "Answer",
        "Requesting permissions…" to "Requesting permissions…",
        "Cancel" to "Cancel",
        "Camera off" to "Camera off",
        "Camera on" to "Camera on",
        "Calling…" to "Calling…",
        "Ringing…" to "Ringing…",
        "Connecting…" to "Connecting…",
        "Microphone permission is required for calls." to "Microphone permission is required for calls.",
        "Camera and microphone permissions are required for video calls." to "Camera and microphone permissions are required for video calls.",
        "Camera permission is required for video calls." to "Camera permission is required for video calls.",
        "Unmute" to "Unmute",
        "Mute" to "Mute",
        "Leave" to "Leave",
        "End call" to "End call",
        "Call History" to "Call History",
        "Group" to "Group",
        "Direct" to "Direct",
        "Video" to "Video",
        "Audio" to "Audio",
        "You" to "You",
        "Remove" to "Remove",
        "Undo remove" to "Undo remove",
        "Start chat with {name}" to "Start chat with {name}",
        "Error: {message}" to "Error: {message}",
        "Search returns..." to "Search returns...",
        "{count} returns" to "{count} returns",
        "{count} requested" to "{count} requested",
        "{count} active" to "{count} active",
        "No returns found." to "No returns found.",
        "Return #{id}" to "Return #{id}",
        "Order" to "Order",
        "Customer" to "Customer",
        "Reason" to "Reason",
        "Refund amount" to "Refund amount",
        "Created" to "Created",
        "Received" to "Received",
        "Refunded" to "Refunded",
        "Notes" to "Notes",
        "{count} return items" to "{count} return items",
        "No item details available." to "No item details available.",
        "Quantity: {count}" to "Quantity: {count}",
        "Requested" to "Requested",
        "Approved" to "Approved",
        "Rejected" to "Rejected",
        "Received" to "Received",
        "Refunded" to "Refunded",
        "Audit Logs" to "Audit Logs",
        "{count} variants" to "{count} variants",
        "{count} orders" to "{count} orders",
        "Search orders..." to "Search orders...",
        "No products found." to "No products found.",
        "No orders found." to "No orders found.",
        "No audit logs found." to "No audit logs found.",
        "Order #{id}" to "Order #{id}",
        "Category" to "Category",
        "SKU" to "SKU",
        "Subtotal" to "Subtotal",
        "Shipping cost" to "Shipping cost",
        "Total" to "Total",
        "Items" to "Items",
        "No items." to "No items.",
        "Payment method" to "Payment method",
        "Payment status" to "Payment status",
        "Shipping address" to "Shipping address",
        "Product #{id}" to "Product #{id}",
        "Search by module..." to "Search by module...",
        "All modules" to "All modules",
        "From" to "From",
        "To" to "To",
        "Colour" to "Colour",
        "Variants" to "Variants",
        "No variants." to "No variants.",
        "Delete variant?" to "Delete variant?",
        "Are you sure you want to delete variant {sku}?" to "Are you sure you want to delete variant {sku}?",
        "Delete product?" to "Delete product?",
        "Are you sure you want to delete {name}? This will also delete its variants." to "Are you sure you want to delete {name}? This will also delete its variants.",
        "Edit product" to "Edit product",
        "Add variant" to "Add variant",
        "Delete" to "Delete",
        "Description:" to "Description:",
        "Colour: {value}" to "Colour: {value}",
        "Weight: {value}" to "Weight: {value}",
        "SKU: {value}" to "SKU: {value}",
        "Stock: {count}" to "Stock: {count}",
    ),
    AppLanguage.RO to mapOf(
        "Dashboard" to "Dashboard",
        "Tasks" to "Taskuri",
        "Workspace" to "Spațiu de lucru",
        "Sales" to "Vânzări",
        "Projects" to "Proiecte",
        "Chat" to "Chat",
        "Stock" to "Stoc",
        "Orders" to "Comenzi",
        "Returns" to "Retururi",
        "Admin" to "Admin",
        "Sign in" to "Autentificare",
        "Email" to "Email",
        "Password" to "Parola",
        "Enter your email" to "Introdu emailul",
        "Enter your password" to "Introdu parola",
        "Login" to "Intră în cont",
        "Could not connect to backend." to "Nu s-a putut conecta la server.",
        "Login failed." to "Autentificarea a eșuat.",
        "Logged in as {name}" to "Conectat ca {name}",
        "Account" to "Cont",
        "Phone" to "Telefon",
        "Phone number" to "Număr de telefon",
        "Phone number is required." to "Numărul de telefon este obligatoriu.",
        "Phone number is too long." to "Numărul de telefon este prea lung.",
        "Status" to "Status",
        "Role" to "Rol",
        "Language" to "Limbă",
        "Log out" to "Delogare",
        "Close" to "Închide",
        "Administrator" to "Administrator",
        "Employee" to "Angajat",
        "Available" to "Disponibil",
        "Busy" to "Ocupat",
        "Away" to "Plecat",
        "Unknown" to "Necunoscut",
        "Good evening, {name}." to "Bună seara, {name}.",
        "Due today" to "De terminat azi",
        "{count} task" to "{count} task",
        "{count} tasks" to "{count} taskuri",
        "No tasks due today." to "Nu sunt taskuri de terminat azi.",
        "Online now" to "Online acum",
        "{count} person" to "{count} persoană",
        "{count} people" to "{count} persoane",
        "No project" to "Fără proiect",
        "Unassigned" to "Nealocat",
        "Search tasks..." to "Caută taskuri...",
        "+ Add task" to "+ Adaugă task",
        "My tasks" to "Taskurile mele",
        "All" to "Toate",
        "To do" to "De făcut",
        "In progress" to "În lucru",
        "Complete" to "Finalizat",
        "Blocked" to "Blocat",
        "Task" to "Task",
        "Add task" to "Adaugă task",
        "Due" to "Deadline",
        "Project" to "Proiect",
        "Assignees" to "Responsabili",
        "Save task" to "Salvează task",
        "Cancel" to "Anulează",
        "Edit task" to "Editează task",
        "Save changes" to "Salvează modificările",
        "Saving..." to "Se salvează...",
        "Description" to "Descriere",
        "Assigned to" to "Alocat către",
        "Subtasks" to "Subtask-uri",
        "Add subtask" to "Adaugă subtask",
        "Subtask title" to "Titlu subtask",
        "Create subtask" to "Creează subtask",
        "No subtasks yet" to "Nu există subtask-uri încă",
        "Delete parent task warning" to "Ștergerea acestui task poate transforma subtask-urile în task-uri principale.",
        "+ Assign" to "+ Alocă",
        "Search by name..." to "Caută după nume...",
        "No users found" to "Nu am găsit utilizatori.",
        "Time tracking" to "Timp lucrat",
        "Total task" to "Total task",
        "Start timer" to "Pornește timer",
        "Stop timer" to "Oprește timer",
        "Search projects..." to "Caută proiecte...",
        "+ Add project" to "+ Adaugă proiect",
        "Deadline" to "Deadline",
        "No tasks in this project yet." to "Nu există taskuri în acest proiect.",
        "Add project" to "Adaugă proiect",
        "Save project" to "Salvează proiect",
        "Search products..." to "Caută produse...",
        "+ Add product" to "+ Adaugă produs",
        "Add product" to "Adaugă produs",
        "Product" to "Produs",
        "Product name" to "Nume produs",
        "Image URL" to "URL imagine",
        "Price" to "Preț",
        "Weight" to "Greutate",
        "Weight unit" to "Unitate greutate",
        "Stock quantity" to "Cantitate în stoc",
        "Out of stock" to "Stoc epuizat",
        "{count} products" to "{count} produse",
        "{count} low stock" to "{count} stoc redus",
        "{count} out of stock" to "{count} fără stoc",
        "Save product" to "Salvează produs",
        "Previous" to "Înapoi",
        "Next" to "Înainte",
        "Edit" to "Editează",
        "Quantity" to "Cantitate",
        "Save" to "Salvează",
        "Add user" to "Adaugă utilizator",
        "Full name" to "Nume complet",
        "Language flag" to "Cod limbă",
        "Save user" to "Salvează utilizator",
        "Search users..." to "Caută utilizatori...",
        "+ Add user" to "+ Adaugă utilizator",
        "User" to "Utilizator",
        "Active" to "Activ",
        "Inactive" to "Inactiv",
        "Actions" to "Acțiuni",
        "Deactivate" to "Dezactivează",
        "Reactivate" to "Reactivează",
        "Deactivate account?" to "Dezactivezi contul?",
        "Reactivate account?" to "Reactivezi contul?",
        "Are you sure you want to deactivate {name}?" to "Sigur vrei să dezactivezi contul lui {name}?",
        "Are you sure you want to reactivate {name}?" to "Sigur vrei să reactivezi contul lui {name}?",
        "Page {page} of {total}" to "Pagina {page} din {total}",
        "{count} users" to "{count} utilizatori",
        "Search chat or person..." to "Caută chat sau persoană...",
        "No chats found." to "Nu am găsit niciun chat.",
        "Write a message..." to "Scrie un mesaj...",
        "Send" to "Trimite",
        "Unknown sender" to "Necunoscut",
        "New group" to "Grup nou",
        "GROUP" to "GRUP",
        "Create group" to "Creează grup",
        "Edit group" to "Editează grupul",
        "Group name" to "Nume grup",
        "Add members" to "Adaugă membri",
        "Current members" to "Membri actuali",
        "Search people..." to "Caută persoane...",
        "Create" to "Creează",
        "Settings" to "Setări",
        "Audio call" to "Apel audio",
        "Video call" to "Apel video",
        "Group audio" to "Audio grup",
        "Group video" to "Video grup",
        "Call history" to "Istoric apeluri",
        "No calls found." to "Nu am găsit apeluri.",
        "Incoming video call" to "Apel video primit",
        "Incoming audio call" to "Apel audio primit",
        "Group call" to "Apel de grup",
        "Lumi Workspace call" to "Apel Lumi Workspace",
        "Decline" to "Refuză",
        "Answer" to "Răspunde",
        "Requesting permissions…" to "Se solicită permisiunile…",
        "Cancel" to "Anulează",
        "Camera off" to "Oprește camera",
        "Camera on" to "Pornește camera",
        "Calling…" to "Se apelează…",
        "Ringing…" to "Sonerie…",
        "Connecting…" to "Se conectează…",
        "Microphone permission is required for calls." to "Este necesară permisiunea pentru microfon.",
        "Camera and microphone permissions are required for video calls." to "Sunt necesare permisiunile pentru cameră și microfon.",
        "Camera permission is required for video calls." to "Este necesară permisiunea pentru cameră.",
        "Unmute" to "Activează microfonul",
        "Mute" to "Dezactivează microfonul",
        "Leave" to "Părăsește",
        "End call" to "Închide apelul",
        "Call History" to "Istoric apeluri",
        "Group" to "Grup",
        "Direct" to "Direct",
        "Video" to "Video",
        "Audio" to "Audio",
        "You" to "Tu",
        "Remove" to "Elimină",
        "Undo remove" to "Anulează eliminarea",
        "Start chat with {name}" to "Începe chat cu {name}",
        "Error: {message}" to "Eroare: {message}",
        "Search returns..." to "Caută retururi...",
        "{count} returns" to "{count} retururi",
        "{count} requested" to "{count} cerute",
        "{count} active" to "{count} active",
        "No returns found." to "Nu am găsit retururi.",
        "Return #{id}" to "Retur #{id}",
        "Order" to "Comandă",
        "Customer" to "Client",
        "Reason" to "Motiv",
        "Refund amount" to "Sumă rambursată",
        "Created" to "Creat",
        "Received" to "Primit",
        "Refunded" to "Rambursat",
        "Notes" to "Notițe",
        "{count} return items" to "{count} produse returnate",
        "No item details available." to "Nu există detalii despre produse.",
        "Quantity: {count}" to "Cantitate: {count}",
        "Requested" to "Cerut",
        "Approved" to "Aprobat",
        "Rejected" to "Respins",
        "Received" to "Primit",
        "Refunded" to "Rambursat",
        "Audit Logs" to "Jurnale audit",
        "{count} variants" to "{count} variante",
        "{count} orders" to "{count} comenzi",
        "Search orders..." to "Caută comenzi...",
        "No products found." to "Nu am găsit produse.",
        "No orders found." to "Nu am găsit comenzi.",
        "No audit logs found." to "Nu am găsit jurnale de audit.",
        "Order #{id}" to "Comandă #{id}",
        "Category" to "Categorie",
        "SKU" to "SKU",
        "Subtotal" to "Subtotal",
        "Shipping cost" to "Cost livrare",
        "Total" to "Total",
        "Items" to "Produse",
        "No items." to "Nu există produse.",
        "Payment method" to "Metodă de plată",
        "Payment status" to "Status plată",
        "Shipping address" to "Adresă livrare",
        "Product #{id}" to "Produs #{id}",
        "Search by module..." to "Caută după modul...",
        "All modules" to "Toate modulele",
        "From" to "De la",
        "To" to "Până la",
        "Colour" to "Culoare",
        "Variants" to "Variante",
        "No variants." to "Nu există variante.",
        "Delete variant?" to "Ștergi varianta?",
        "Are you sure you want to delete variant {sku}?" to "Sigur vrei să ștergi varianta {sku}?",
        "Delete product?" to "Ștergi produsul?",
        "Are you sure you want to delete {name}? This will also delete its variants." to "Sigur vrei să ștergi {name}? Se vor șterge și variantele.",
        "Edit product" to "Editează produs",
        "Add variant" to "Adaugă variantă",
        "Delete" to "Șterge",
        "Description:" to "Descriere:",
        "Colour: {value}" to "Culoare: {value}",
        "Weight: {value}" to "Greutate: {value}",
        "SKU: {value}" to "SKU: {value}",
        "Stock: {count}" to "Stoc: {count}",
    ),
    AppLanguage.DE to mapOf(
        "Dashboard" to "Dashboard",
        "Tasks" to "Aufgaben",
        "Workspace" to "Arbeitsbereich",
        "Sales" to "Vertrieb",
        "Projects" to "Projekte",
        "Chat" to "Chat",
        "Stock" to "Lager",
        "Orders" to "Bestellungen",
        "Returns" to "Retouren",
        "Admin" to "Admin",
        "Sign in" to "Anmelden",
        "Email" to "E-Mail",
        "Password" to "Passwort",
        "Enter your email" to "E-Mail eingeben",
        "Enter your password" to "Passwort eingeben",
        "Login" to "Einloggen",
        "Could not connect to backend." to "Keine Verbindung zum Server möglich.",
        "Login failed." to "Anmeldung fehlgeschlagen.",
        "Logged in as {name}" to "Angemeldet als {name}",
        "Account" to "Konto",
        "Phone" to "Telefon",
        "Phone number" to "Telefonnummer",
        "Phone number is required." to "Telefonnummer ist erforderlich.",
        "Phone number is too long." to "Telefonnummer ist zu lang.",
        "Status" to "Status",
        "Role" to "Rolle",
        "Language" to "Sprache",
        "Log out" to "Abmelden",
        "Close" to "Schließen",
        "Administrator" to "Administrator",
        "Employee" to "Mitarbeiter",
        "Available" to "Verfügbar",
        "Busy" to "Beschäftigt",
        "Away" to "Abwesend",
        "Unknown" to "Unbekannt",
        "Good evening, {name}." to "Guten Abend, {name}.",
        "Due today" to "Heute fällig",
        "{count} task" to "{count} Aufgabe",
        "{count} tasks" to "{count} Aufgaben",
        "No tasks due today." to "Heute sind keine Aufgaben fällig.",
        "Online now" to "Jetzt online",
        "{count} person" to "{count} Person",
        "{count} people" to "{count} Personen",
        "No project" to "Kein Projekt",
        "Unassigned" to "Nicht zugewiesen",
        "Search tasks..." to "Aufgaben suchen...",
        "+ Add task" to "+ Aufgabe hinzufügen",
        "My tasks" to "Meine Aufgaben",
        "All" to "Alle",
        "To do" to "Zu erledigen",
        "In progress" to "In Arbeit",
        "Complete" to "Abgeschlossen",
        "Blocked" to "Blockiert",
        "Task" to "Aufgabe",
        "Add task" to "Aufgabe hinzufügen",
        "Due" to "Fällig",
        "Project" to "Projekt",
        "Assignees" to "Zugewiesen an",
        "Save task" to "Aufgabe speichern",
        "Cancel" to "Abbrechen",
        "Edit task" to "Aufgabe bearbeiten",
        "Save changes" to "Änderungen speichern",
        "Saving..." to "Speichert...",
        "Description" to "Beschreibung",
        "Assigned to" to "Zugewiesen an",
        "Subtasks" to "Unteraufgaben",
        "Add subtask" to "Unteraufgabe hinzufügen",
        "Subtask title" to "Unteraufgabentitel",
        "Create subtask" to "Unteraufgabe erstellen",
        "No subtasks yet" to "Noch keine Unteraufgaben",
        "Delete parent task warning" to "Das Löschen dieser Aufgabe kann Unteraufgaben zu Hauptaufgaben machen.",
        "+ Assign" to "+ Zuweisen",
        "Search by name..." to "Nach Namen suchen...",
        "No users found" to "Keine Benutzer gefunden.",
        "Time tracking" to "Zeiterfassung",
        "Total task" to "Aufgabe gesamt",
        "Start timer" to "Timer starten",
        "Stop timer" to "Timer stoppen",
        "Search projects..." to "Projekte suchen...",
        "+ Add project" to "+ Projekt hinzufügen",
        "Deadline" to "Deadline",
        "No tasks in this project yet." to "Noch keine Aufgaben in diesem Projekt.",
        "Add project" to "Projekt hinzufügen",
        "Save project" to "Projekt speichern",
        "Search products..." to "Produkte suchen...",
        "+ Add product" to "+ Produkt hinzufügen",
        "Add product" to "Produkt hinzufügen",
        "Product" to "Produkt",
        "Product name" to "Produktname",
        "Image URL" to "Bild-URL",
        "Price" to "Preis",
        "Weight" to "Gewicht",
        "Weight unit" to "Gewichtseinheit",
        "Stock quantity" to "Lagerbestand",
        "Out of stock" to "Nicht auf Lager",
        "{count} products" to "{count} Produkte",
        "{count} low stock" to "{count} niedriger Bestand",
        "{count} out of stock" to "{count} nicht auf Lager",
        "Save product" to "Produkt speichern",
        "Previous" to "Zurück",
        "Next" to "Weiter",
        "Edit" to "Bearbeiten",
        "Quantity" to "Menge",
        "Save" to "Speichern",
        "Add user" to "Benutzer hinzufügen",
        "Full name" to "Vollständiger Name",
        "Language flag" to "Sprachcode",
        "Save user" to "Benutzer speichern",
        "Search users..." to "Benutzer suchen...",
        "+ Add user" to "+ Benutzer hinzufügen",
        "User" to "Benutzer",
        "Active" to "Aktiv",
        "Inactive" to "Inaktiv",
        "Actions" to "Aktionen",
        "Deactivate" to "Deaktivieren",
        "Reactivate" to "Reaktivieren",
        "Deactivate account?" to "Konto deaktivieren?",
        "Reactivate account?" to "Konto reaktivieren?",
        "Are you sure you want to deactivate {name}?" to "Möchtest du {name} wirklich deaktivieren?",
        "Are you sure you want to reactivate {name}?" to "Möchtest du {name} wirklich reaktivieren?",
        "Page {page} of {total}" to "Seite {page} von {total}",
        "{count} users" to "{count} Benutzer",
        "Search chat or person..." to "Chat oder Person suchen...",
        "No chats found." to "Keine Chats gefunden.",
        "Write a message..." to "Nachricht schreiben...",
        "Send" to "Senden",
        "Unknown sender" to "Unbekannt",
        "New group" to "Neue Gruppe",
        "GROUP" to "GRUPPE",
        "Create group" to "Gruppe erstellen",
        "Edit group" to "Gruppe bearbeiten",
        "Group name" to "Gruppenname",
        "Add members" to "Mitglieder hinzufügen",
        "Current members" to "Aktuelle Mitglieder",
        "Search people..." to "Personen suchen...",
        "Create" to "Erstellen",
        "Settings" to "Einstellungen",
        "Audio call" to "Audioanruf",
        "Video call" to "Videoanruf",
        "Group audio" to "Gruppenaudio",
        "Group video" to "Gruppenvideo",
        "Call history" to "Anrufverlauf",
        "No calls found." to "Keine Anrufe gefunden.",
        "Incoming video call" to "Eingehender Videoanruf",
        "Incoming audio call" to "Eingehender Audioanruf",
        "Group call" to "Gruppenanruf",
        "Lumi Workspace call" to "Lumi Workspace-Anruf",
        "Decline" to "Ablehnen",
        "Answer" to "Annehmen",
        "Requesting permissions…" to "Berechtigungen werden angefordert…",
        "Cancel" to "Abbrechen",
        "Camera off" to "Kamera aus",
        "Camera on" to "Kamera ein",
        "Calling…" to "Wird angerufen…",
        "Ringing…" to "Klingelt…",
        "Connecting…" to "Verbindung wird hergestellt…",
        "Microphone permission is required for calls." to "Mikrofonberechtigung ist für Anrufe erforderlich.",
        "Camera and microphone permissions are required for video calls." to "Kamera- und Mikrofonberechtigung sind für Videoanrufe erforderlich.",
        "Camera permission is required for video calls." to "Kameraberechtigung ist für Videoanrufe erforderlich.",
        "Unmute" to "Stummschaltung aufheben",
        "Mute" to "Stummschalten",
        "Leave" to "Verlassen",
        "End call" to "Anruf beenden",
        "Call History" to "Anrufverlauf",
        "Group" to "Gruppe",
        "Direct" to "Direkt",
        "Video" to "Video",
        "Audio" to "Audio",
        "You" to "Du",
        "Remove" to "Entfernen",
        "Undo remove" to "Entfernen rückgängig",
        "Start chat with {name}" to "Chat mit {name} starten",
        "Error: {message}" to "Fehler: {message}",
        "Search returns..." to "Retouren suchen...",
        "{count} returns" to "{count} Retouren",
        "{count} requested" to "{count} angefragt",
        "{count} active" to "{count} aktiv",
        "No returns found." to "Keine Retouren gefunden.",
        "Return #{id}" to "Retoure #{id}",
        "Order" to "Bestellung",
        "Customer" to "Kunde",
        "Reason" to "Grund",
        "Refund amount" to "Erstattungsbetrag",
        "Created" to "Erstellt",
        "Received" to "Erhalten",
        "Refunded" to "Erstattet",
        "Notes" to "Notizen",
        "{count} return items" to "{count} Retourenartikel",
        "No item details available." to "Keine Artikeldetails verfügbar.",
        "Quantity: {count}" to "Menge: {count}",
        "Requested" to "Angefragt",
        "Approved" to "Genehmigt",
        "Rejected" to "Abgelehnt",
        "Received" to "Erhalten",
        "Refunded" to "Erstattet",
        "Audit Logs" to "Audit-Protokolle",
        "{count} variants" to "{count} Varianten",
        "{count} orders" to "{count} Bestellungen",
        "Search orders..." to "Bestellungen suchen...",
        "No products found." to "Keine Produkte gefunden.",
        "No orders found." to "Keine Bestellungen gefunden.",
        "No audit logs found." to "Keine Audit-Protokolle gefunden.",
        "Order #{id}" to "Bestellung #{id}",
        "Category" to "Kategorie",
        "SKU" to "SKU",
        "Subtotal" to "Zwischensumme",
        "Shipping cost" to "Versandkosten",
        "Total" to "Gesamt",
        "Items" to "Artikel",
        "No items." to "Keine Artikel.",
        "Payment method" to "Zahlungsmethode",
        "Payment status" to "Zahlungsstatus",
        "Shipping address" to "Lieferadresse",
        "Product #{id}" to "Produkt #{id}",
        "Search by module..." to "Nach Modul suchen...",
        "All modules" to "Alle Module",
        "From" to "Von",
        "To" to "Bis",
        "Colour" to "Farbe",
        "Variants" to "Varianten",
        "No variants." to "Keine Varianten.",
        "Delete variant?" to "Variante löschen?",
        "Are you sure you want to delete variant {sku}?" to "Möchtest du die Variante {sku} wirklich löschen?",
        "Delete product?" to "Produkt löschen?",
        "Are you sure you want to delete {name}? This will also delete its variants." to "Möchtest du {name} wirklich löschen? Die Varianten werden ebenfalls gelöscht.",
        "Edit product" to "Produkt bearbeiten",
        "Add variant" to "Variante hinzufügen",
        "Delete" to "Löschen",
        "Description:" to "Beschreibung:",
        "Colour: {value}" to "Farbe: {value}",
        "Weight: {value}" to "Gewicht: {value}",
        "SKU: {value}" to "SKU: {value}",
        "Stock: {count}" to "Bestand: {count}",
    ),
)
